### ISSUE TITLE
Download site for pre-trained model is completely in chinese

### ISSUE THREAD

**Issue by YacobBY** [zealerww/gender_age_classification#2]
Tthe pre-trained model download link redirects to Baidu's completely Chinese site. When I try to press the button with a download icon it tries to download some Baidu installer and not the model. Could you reupload the pre-trained model to something like Google Drive?

**Comment by YacobBY** [comment]
Thanks!

**Comment by zealerww** [comment]
sorry， i gave a wrong link. i will upload the model and give you a new link.

**Comment by zealerww** [comment]
new link: https://drive.google.com/file/d/1swNHi9XMh0GJs8eBEhw2xjCAN07JjfT9/view?usp=sharing
